[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests

# Coverage settings
addopts =
    --tb=short
    --strict-markers
    --cov=apps
    --cov-report=term-missing
    --cov-report=html:var/coverage/htmlcov
    --cov-report=xml:var/coverage/coverage.xml
    --cov-fail-under=95

# Warning filters
filterwarnings =
    error
    ignore::DeprecationWarning:kombu.*:
    ignore::DeprecationWarning:celery.*:
    ignore::DeprecationWarning:amqp.*:
    ignore::PendingDeprecationWarning:celery.*:

# Markers
markers =
    unit: Unit tests
    integration: Integration tests
    slow: Slow running tests

# Django settings
django_find_project = false
