# Generated by Django 5.2.8 on 2025-11-28 06:34

import apps.documents.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Удалён"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/",
                        validators=[
                            apps.documents.validators.validate_file_extension_safety
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF документ"),
                            ("docx", "Word документ"),
                            ("txt", "Текстовый файл"),
                            ("image", "Изображение"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="Размер в байтах", verbose_name="Размер файла"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает проверки"),
                            ("approved", "Подтверждён"),
                            ("rejected", "Отклонён"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Исходное имя файла"),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Заполняется при отклонении документа",
                        verbose_name="Причина отклонения",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата проверки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
